/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo.application;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.util.Properties;

import todo.application.business.TodoApplication;
import todo.application.data.access.impl.TodoDataAccessImpl;
import todo.application.data.entity.TodoTask;
import todo.application.exceptions.TodoApplicationException;
import todo.application.util.DateUtil;

public class App
{
	private static final String DASH_LINE = "-------------------------------------------------------------";
	private static PrintStream console = System.out;
	private static PrintStream error = System.err;
	private static String datePattern;

	public static void main( String[] args ) throws TodoApplicationException, IOException
	{
		boolean isContinue = true;
		Properties properties = getApplicationProperties();
		datePattern = properties.getProperty( "date.pattern" );
		DateUtil dateUtil = new DateUtil( datePattern );
		TodoDataAccessImpl dataAccess = new TodoDataAccessImpl();
		TodoApplication todoApp = new TodoApplication( dataAccess, dateUtil );

		console.println( DASH_LINE );
		console.println( "Welcome to Todo Application" );
		console.println( DASH_LINE );

		while ( isContinue )
		{
			console.println( "\n\n(view[v], add[a], mark[m], delete[d], quit[q])" );
			console.println( DASH_LINE );
			String userCommand = getInputFromConsole( "Enter your choice [view]:" );
			if ( isMatchingCommand( userCommand, "quit", "q" ) )
			{
				console.println( "Bye Bye!" );
				isContinue = false;
			}
			else if ( isMatchingCommand( userCommand, "add", "a" ) )
			{
				addTodoTask( todoApp );
			}
			else if ( isMatchingCommand( userCommand, "view", "v" ) || userCommand.length() == 0 )
			{
				viewTodoTask( todoApp );
			}
			else if ( isMatchingCommand( userCommand, "mark", "m" ) )
			{
				markTodoTask( todoApp );

			}
			else if ( isMatchingCommand( userCommand, "delete", "d" ) )
			{
				deleteTodoTask( todoApp );
			}
			else
			{
				console.println( String.format( "%s is not a valid command", userCommand ) );
			}
		}
	}

	protected static Properties getApplicationProperties() throws TodoApplicationException
	{
		try
		{
			ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
			InputStream inputStream = classLoader.getResourceAsStream( "application.properties" );
			Properties properties = new Properties();
			properties.load( inputStream );
			return properties;
		}
		catch ( IOException e )
		{
			throw new TodoApplicationException( "Error while loading application.properties", e );
		}
	}

	protected static boolean isMatchingCommand( String userCommand, String longCmd, String shortCmd )
	{
		return userCommand.equals( longCmd ) || userCommand.equals( shortCmd );
	}

	protected static void addTodoTask( TodoApplication todoApp )
	{
		try
		{
			String taskName = getInputFromConsole( "Enter task name to add:" );
			String targetDateStr = getInputFromConsole( String.format( "Enter target date [format:%s]:", datePattern ) );
			TodoTask todoTask = todoApp.createTodoTask( taskName, targetDateStr );
			console.println( todoTask );
			console.println( "Todo task created!" );
		}
		catch ( TodoApplicationException e )
		{
			error.println( e.getMessage() );
		}
	}

	protected static void deleteTodoTask( TodoApplication todoApp )
	{
		try
		{
			Long taskId = getTodoTaskId( "Enter task id to delete:" );
			todoApp.deleteTodoTask( taskId );
			console.println( String.format( "Task with id %d deleted!", taskId ) );
		}
		catch ( TodoApplicationException e )
		{
			error.println( e.getMessage() );
		}
	}

	protected static void markTodoTask( TodoApplication todoApp )
	{
		try
		{
			Long taskId = getTodoTaskId( "Enter task id to mark complete:" );
			String completionDateStr = getInputFromConsole( String.format( "Enter complete date [format:%s]:", datePattern ) );
			todoApp.updateTodoTask( taskId, completionDateStr );
			console.println( String.format( "Task with id %d marked complete!", taskId ) );
		}
		catch ( TodoApplicationException e )
		{
			error.println( e.getMessage() );
		}
	}

	protected static void viewTodoTask( TodoApplication todoApp )
	{
		try
		{
			String taskIdStr = getInputFromConsole( "Enter task id to view:" );
			if ( taskIdStr.isEmpty() || taskIdStr.equals( "\n" ) )
			{
				for ( TodoTask todoTask : todoApp.getAllTodoTasks() )
				{
					console.println( todoTask );
				}
			}
			else
			{
				Long taskId = Long.parseLong( taskIdStr );
				TodoTask todoTask = todoApp.getTodoTask( taskId );
				console.println( todoTask );
			}
		}
		catch ( NumberFormatException e )
		{
			error.println( "That was not a valid task Id" );
		}
		catch ( TodoApplicationException e )
		{
			error.println( e.getMessage() );
		}
	}

	protected static String getInputFromConsole( String message ) throws TodoApplicationException
	{
		try
		{
			BufferedReader consoleReader = new BufferedReader( new InputStreamReader( System.in ) );
			console.print( message );
			return consoleReader.readLine();
		}
		catch ( IOException e )
		{
			throw new TodoApplicationException( e );
		}
	}

	protected static long getTodoTaskId( String message ) throws TodoApplicationException
	{
		String taskIdStr = "";
		try
		{
			taskIdStr = getInputFromConsole( message );
			return Long.parseLong( taskIdStr );
		}
		catch ( NumberFormatException e )
		{
			throw new TodoApplicationException( String.format( "Task Id must be a number, %s is not a valid number", taskIdStr ) );
		}
	}
}
